// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnowqhgufhbeccdlctxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZub3dxaGd1ZmhiZWNjZGxjdHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTUwMjcsImV4cCI6MjA2NjE5MTAyN30.Gyep7hLEAtMRvgjBHNcM_1aSd517oLQPC2JXHW9JmO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);